# Custom values for kube-prometheus-stack
grafana:
  adminPassword: "1"
  defaultDashboardsEnabled: false
  service:
    type: NodePort
  # 1. TEST CHANGE: Change this label to see ArgoCD detect a metadata change
  podLabels:
    gitops-status: "all-bad"

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    # 2. TEST CHANGE: Change this value to see it appear in the Prometheus UI
    externalLabels:
      cluster_env: "minikube-dev"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

alertmanager:
  alertmanagerSpec:
    # 3. TEST CHANGE: Scale this from 1 to 2 to see pods being created
    replicas: 5